import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./conponents/Nav/Navbar.";
import LayoutProvider from "./provider/LayoutProvider";
import { ToastContainer, toast } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider >
          {children}
          <ToastContainer />
        </LayoutProvider>
      </body>
    </html>
  );
}
